---
AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  AWS CloudFormation Cross-Stack Reference Sample Template  Weserver_EC2_Instance: This 
  template provisions an webserver EC2 instance in a public subnet and using an EC2 Security Group 
  provisioned in a different stack. Note that you will be billed for the AWS resources used if you create a stack from this template. 
Parameters:
  NetworkStackName:
    Description: Name of CloudFormation stack that contains the networking resources, such as the subnet and security group, that will be used in this stack
    Type: String
    Default : SampleNetworkCrossStack

  SecurityGroupDescription:
    Description: SSH SecurityGroupDescription
    Type: String

  SecurityGroupPort:
    Description: Allow ssh from my IP
    Type: Number
    MinValue: 20
    MaxValue: 65535

  SecurityGroupIngressCIDR:
    Description: Your IP address
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

  InstanceType:
    Description: EC2 instance type Default is t2.micro.
    Type: String
    Default: t2.micro
    AllowedValues: # possible values 
      - t2.micro
      - t2.nano
      - t2.small
    ConstraintDescription: must be a valid EC2 instance type.

  MyKeyName: 
    Description: Amazon EC2 Key Pair
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 keypair.

 
Mappings: 
  RegionMap: 
    us-east-1:
      HVM64: ami-033b95fb8079dc481
    us-east-2:
      HVM64: ami-0b614a5d911900a9b
    us-west-1:
      HVM64: ami-0573b70afecda915d
    eu-west-1:
      HVM64: ami-0bf84c42e04519c85
    ap-northeast-1:
      HVM64: ami-08a8688fb7eacb171
    ap-southeast-1:
      HVM64: ami-02a45d709a415958a

Resources: 
  MyWebserverInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref MyKeyName
      SubnetId: !ImportValue SampleNetworkCrossStack-SubnetID
      SecurityGroupIds:  
        - !ImportValue  SampleNetworkCrossStack-SecurityGroupID
        
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", HVM64]  
      UserData:
        Fn::Base64: |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            echo "hello World!" > /var/www/html/index.html
      Tags: 
          - Key: Name
            Value: "Linux-webserver-EC2-launched-by-cloudformation"
  MySSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
        - CidrIp: !Ref SecurityGroupIngressCIDR
          IpProtocol: tcp
          FromPort: !Ref SecurityGroupPort
          ToPort: !Ref SecurityGroupPort
      VpcId: !ImportValue SampleNetworkCrossStack-VPCID  
  ElasticIP: 
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MyWebserverInstance

     
Outputs:
  WebserverPrivateIPaddress:
    Description: The private IP of the EC2
    Value: !GetAtt MyWebserverInstance.PrivateIp
    Export:
      Name: WebserverIP
  WebserverDnsname:
    Description: The Public DNS Name of the specified instance 
    Value: !GetAtt MyWebserverInstance.PublicDnsName
    Export:
      Name: WebserverDnsName
  